# Generated by Django 3.2.3 on 2021-05-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('dist_name', models.CharField(max_length=50)),
                ('dist_code', models.SmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('pin_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.dist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('d1', models.BooleanField(default=True)),
                ('d2', models.BooleanField(default=True)),
                ('notify', models.BooleanField()),
                ('eight', models.BooleanField()),
                ('five', models.BooleanField()),
                ('cvsh', models.BooleanField()),
                ('covax', models.BooleanField()),
                ('sptk', models.BooleanField()),
                ('free', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.pin')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField()),
                ('day_numb', models.SmallIntegerField()),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cent_id', models.IntegerField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.day')),
            ],
        ),
    ]
