# Generated by Django 3.2.3 on 2021-05-30 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_times',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 9, 19, 14, 959267, tzinfo=utc)),
        ),
    ]
