# Generated by Django 3.2.3 on 2021-05-31 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_auto_20210530_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dist_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=50)),
                ('dist_numb', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 23, 7, 46, 597760, tzinfo=utc)),
        ),
    ]
