# Generated by Django 3.2.3 on 2021-05-31 05:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_auto_20210531_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j', models.SmallIntegerField()),
                ('k', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 23, 26, 33, 740496, tzinfo=utc)),
        ),
    ]
