# Generated by Django 3.2.3 on 2021-05-31 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_auto_20210531_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.date(2021, 5, 31))),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 0, 54, 6, 21275, tzinfo=utc)),
        ),
    ]
